### ISSUE TITLE
Texture coords

### ISSUE THREAD

**Issue by netcodedev** [bonsairobo/fast-surface-nets-rs#21]
Hi bonsairobo,
Great work on this library!
I was wondering how i would calculate texture coords for the vertices. Could you provide some assistance on that?

**Comment by bonsairobo** [comment]
That's a tricky problem that I haven't tried solving directly.

What you could do is use triplanar mapping. I have an example [here](https://github.com/bonsairobo/bevy_triplanar_splatting).

**Comment by netcodedev** [comment]
Do you have any plans on adding that to the library?

**Comment by bonsairobo** [comment]
Triplanar mapping? No I figured that's handled better with shaders. 

I don't have any plans to augment this library at the moment.

**Comment by netcodedev** [comment]
Alright. Thank you
