### ISSUE TITLE
How to color the resulting meshes / how to give individual vertices a color and blend between them?

### ISSUE THREAD

**Issue by nerdachse** [bonsairobo/fast-surface-nets-rs#9]
Hey there!

First off: Thanks for this amazing crate.

Now I am wondering how could one implement coloring individual vertices. Not even talking about textures and blending right now, just plain ol' colors.

I can give each voxel a color, but as meshing via `surface_nets` wouldn't care, I would need another way to bring the "voxel-material"/color to the mesh.

Any ideas?

**Comment by bonsairobo** [comment]
The mesh buffer contains voxel coordinates for each vertex, so you can use that to look up voxel colors and assign them to a vertex attribute, which can be blended by the render pipeline.

**Comment by nerdachse** [comment]
Thanks, so in it's basic form this follows:

```rust
surface_nets(
    &padded_sdf,
    &PaddedChunkShape {},
    [0; 3],
    [PADDED_CHUNK_SIDE - 1; 3],
    &mut buffer,
);

if buffer.positions.is_empty() {
    return;
}

let mut colors = Vec::with_capacity(buffer.positions.len());

for _pos in buffer.positions.iter() {
    let mut rng = rand::thread_rng();
    let color = Color::rgb(
        rand::Rng::gen_range(&mut rng, 0.0..=1.0),
        rand::Rng::gen_range(&mut rng, 0.0..=1.0),
        rand::Rng::gen_range(&mut rng, 0.0..=1.0),
    );

    colors.extend_from_slice(&[color.as_rgba_f32()]);
}
```

and then:

```rust
mesh.insert_attribute(
    Mesh::ATTRIBUTE_COLOR,
    VertexAttributeValues::Float32x4(colors),
);
```

Sorry for opening an issue, I thought I was missing some built in functionality to avoid iterating the positions again. Maybe we can make this a discussion instead? Or feel free to close, as you wish!

Thanks again for the support!

**Comment by bonsairobo** [comment]
I'm referring to `SurfaceNetsBuffer::surface_strides` or `surface_points`. These arrays are parallel to `positions` and `normals`, as in `buf.surface_strides[i]` is the chunk index for the vertex with position `buf.positions[i]`. So if your voxels have a way of determining color, you can index your voxel chunk using `surface_strides` or `surface_points` to get the color corresponding to the same vertex in the mesh.

**Comment by nerdachse** [comment]
I see, thanks. So for anyone wondering it's basically:

```rust
let mut colors = Vec::with_capacity(buffer.positions.len());
for pos in buffer.surface_strides.iter() {
    let index = *pos as usize;
    let voxel_data = padded_sdf[index];
    let color = match voxel_data.material {
        VoxelMaterial::Nothing => {
            Color::BLACK
        }
        VoxelMaterial::Soil => {
            Color::ORANGE_RED
        }
        VoxelMaterial::Grass => {
            Color::SEA_GREEN
        }
        VoxelMaterial::Metal => {
            Color::DARK_GRAY
        }
    };
    colors.extend_from_slice(&[color.as_rgba_f32()]);
}

```
